# Generated by Django 5.0.4 on 2024-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목 없음', max_length=50)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
