# Generated by Django 5.0.4 on 2024-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0007_rename_data_usermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rank',
            field=models.IntegerField(default='', max_length=101),
        ),
    ]
