# Generated by Django 5.0.4 on 2024-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0008_usermodel_password2_alter_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='rank',
            field=models.IntegerField(default=''),
        ),
    ]
