# Generated by Django 5.0.4 on 2024-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0009_alter_usermodel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
