# Generated by Django 5.0.4 on 2024-04-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0011_userrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='rank',
        ),
    ]
