# Generated by Django 5.0.4 on 2024-04-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0012_remove_usermodel_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date',
        ),
    ]
