# Generated by Django 5.0.4 on 2024-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0014_remove_usermodel_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
