# Generated by Django 5.0.6 on 2024-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0017_video_upload_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
