# Generated by Django 5.0.6 on 2024-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0018_delete_document_remove_usermodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
